def intToRoman(num):
    roman = ""
    if num >= 1000:
        x = (num // 1000)
        num -= x * 1000
        roman += x * "M"
    if num >= 900:
        num -= 900
        roman += "CM"
    if num >= 500:
        num -= 500
        roman += "D"
    if num >= 400:
        num -= 400
        roman += "CD"
    if num >= 100:
        x = (num // 100)
        num -= x * 100
        roman += x * "C"
    if num >= 90:
        num -= 90
        roman += "XC"
    if num >= 50:
        num -= 50
        roman += "L"
    if num >= 40:
        num -= 40
        roman += "XL"
    if num >= 10:
        x = (num // 10)
        num -= x * 10
        roman += x * "X"
    if num >= 9:
        num -= 9
        roman += "IX"
    if num >= 5:
        num -= 5
        roman += "V"
    if num >= 4:
        num -= 4
        roman += "IV"
    if num >= 1:
        roman += num * "I"
    return roman
